spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springdatajpa
    username: root
    password: Dinesh123@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update 
    
  devtools:
    restart:
      enabled: false
    
 
    